// <auto-generated />
using APIfret.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APIfret.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250219012845_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("APIfret.Entities.Ile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codezonetarifaire")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Intitule")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Iles");
                });

            modelBuilder.Entity("APIfret.Entities.TarifFret", b =>
                {
                    b.Property<string>("Case")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("IleArriveeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IleDepartId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Montant")
                        .HasColumnType("TEXT");

                    b.HasIndex("IleArriveeId");

                    b.HasIndex("IleDepartId");

                    b.ToTable("TarifFrets");
                });

            modelBuilder.Entity("APIfret.Entities.TarifsRevatua", b =>
                {
                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Intitule")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Refrigere")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TauxPriseEnCharge")
                        .HasColumnType("INTEGER");

                    b.ToTable("Tarifsrevatuas");
                });

            modelBuilder.Entity("APIfret.Entities.TarifFret", b =>
                {
                    b.HasOne("APIfret.Entities.Ile", "IleArrivee")
                        .WithMany()
                        .HasForeignKey("IleArriveeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APIfret.Entities.Ile", "IleDepart")
                        .WithMany()
                        .HasForeignKey("IleDepartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IleArrivee");

                    b.Navigation("IleDepart");
                });
#pragma warning restore 612, 618
        }
    }
}
